### ISSUE TITLE
create deployment workflow

### ISSUE THREAD

**Issue by tomkralidis** [geopython/demo.pycsw.org#1]
cc @wildintellect @kalxas 

It would be great to provide an automated deployment for projects to deploy http://demo.pycsw.org with something like Docker and / or ansible, or something else.  Note that the workflow is already [documented](https://github.com/geopython/demo.pycsw.org#demopycsworg).

As well, given http://demo.pycsw.org currently runs on OSGeo infrastructure alongside other [projects](http://wiki.osgeo.org/wiki/ProjectsVM) / [demos](http://wiki.osgeo.org/wiki/AdhocVM), this can serve as a workflow for other projects to easily deploy on to OSGeo.

**Comment by tomkralidis** [comment]
cc @robe2

Update: note that OSGeo SAC will provide the ability for us to deploy via Docker.

**Comment by tomkralidis** [comment]
cc @kalxas 

Updates:
- OSGeo VM setup by [SAC](https://trac.osgeo.org/osgeo/ticket/2452) (thanks @robe !)
- new [deploy](https://github.com/geopython/demo.pycsw.org/tree/deploy) branch
  - thins out old/not used services and artifacts
  - updates various deps (JS/CSS)

Staging instance at http://staging.demo.pycsw.osgeo.org

The basic workflow is running `docker-compose up`, which will start up the website and run the CITE instance through an nginx proxy. The CITE instance runs the [default pycsw Docker image](https://hub.docker.com/r/geopython/pycsw/) with a custom configuration for CITE testing

Todo:
- [ ] clarify pycsw's Docker build setup
- [ ] implement continuous deployment
- [ ] switchover staging to live
- [ ] decommission legacy demo site

**Comment by kalxas** [comment]
thanks to @tomkralidis @robe and SAC for their help.

**Comment by tomkralidis** [comment]
FYI switchover complete.  Thanks!
